version: '3.8'

services:
  psql:
    image: postgres
    container_name: 'psql'
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cars

  app:
    container_name: 'pahan'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql