version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'psql'
    volumes:
      - ./migrations/create.sql:/docker-entrypoint-initdb.d/create.sql:ro
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cars

  app:
    container_name: 'pahan'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql
