// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/get_factories": {
            "get": {
                "description": "Get all factories with current vendorID",
                "summary": "list of factories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of a vendor",
                        "name": "vendor-id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Factory"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/v1/get_types": {
            "get": {
                "description": "Get all types",
                "summary": "list of types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Type"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Factory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "max_workers": {
                    "type": "integer"
                },
                "productivity": {
                    "type": "integer"
                },
                "vendor_id": {
                    "type": "integer"
                }
            }
        },
        "entity.Type": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "pahan_internal_controller_http_v1.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Автомобилестроение в экономике",
	Description:      "Курсовая работа по предмету \"Информационные системы и базы данных\" студента группы P34312, Соловьева Павла",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
